#!/usr/bin/env bash
INSTALL_DIR=/home/user/etc
PROJECT_NAME=baerDavid
INSTALL_BIN=/home/user/bin
BIN_NAME=baerDavid
#export PATH="$PATH:$INSTALL_BIN"


Install()
{
    #make folder for install
    mkdir -p $INSTALL_DIR/$PROJECT_NAME
    mkdir -p $INSTALL_BIN

    #put bin into bin
    cp $BIN_NAME $INSTALL_BIN/

    #put all install files in etc
    cp -r * $INSTALL_DIR/$PROJECT_NAME/

    cd $INSTALL_DIR/$PROJECT_NAME/

    #ARG='export PATH="$PATH:/home/user/etc"'
    #python3 addPath.py $ARG
    #source ~/catkin_ws/devel/setup.sh

    export PATH="$PATH:$INSTALL_BIN"
    export PATH="$PATH:$INSTALL_DIR"

}

Uninstall()
{
    rm -r $INSTALL_DIR/$PROJECT_NAME
    rm $INSTALL_BIN/$BIN_NAME

    
    PATH=${PATH//":$INSTALL_BIN:"/":"} # delete any instances in the middle
    PATH=${PATH/#"$INSTALL_BIN:"/} # delete any instance at the beginning
    PATH=${PATH/%":$INSTALL_BIN"/} # delete any instance in the at the end
    #source ~/.bashrc
    #echo $PATH
}
Start()
{
    cd $INSTALL_DIR/$PROJECT_NAME/final

    echo 'loading level'
    ./final.sh
    cd ..

    echo 'loading robot'
    ./loadModel.sh
    cd src

    echo 'loading controller'
    sleep 2
    python allDrive_Keyboard_Controller.py

    
}


Stop()
{
    cd $INSTALL_DIR/$PROJECT_NAME

    echo 'removing robot'
    ./rmModel.sh
    cd final

    echo 'removing level'
    ./finalRemove.sh
}



Help()
{
    echo ' '
    echo ' '
    echo '--------------baerDavid------------'
    echo '-----------fourWheelRobot----------'
    echo 'install       :install the program '
    echo 'help          :run help            '
    echo 'start         :starts program      '
    echo 'uninstall     :uninstalls          '
    echo 'stop          :stops program       '
    echo ' '
    echo ' '
    exit 0
}


case $1 in 
'install')
    Install
    ;;
'uninstall')
    Uninstall
    ;;
'start')
    Start
    ;;
'help')
    Help
    ;;
'stop')
    Stop
    ;;
*)
    Help
    ;;
esac
exit 0